---
title: "Untitled"
author: "Benny"
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(childesr)
library(text2vec)
library(word2vec)
library(viridis)

project_root <- here::here()


```


```{r}
d_utterances <- 
  get_utterances(collection = "Eng-NA")

d_participants <- get_participants(collection = "Eng-NA")

d_children <- 
  d_participants %>% 
  filter(role == "Target_Child")

```

```{r}
d_utterances_arranged <- 
  d_utterances %>% 
  arrange(transcript_id, utterance_order) %>% 
  filter(speaker_role %in% c(
    "Mother",
    "Grandmother",
    "Father",
    "Adult"
  ))

groups <- 
  d_utterances_arranged %>% 
  group_by(transcript_id) %>%
  group_split

collapse_words <- function(transcript) {
  return(transcript %>% pull(stem) %>% paste(collapse = " "))
} 



#make a list of all of the transcripts
transcript_list <- 
  groups %>% 
  map(collapse_words)

write_file(
  transcript_list %>% paste(collapse = "\n\n"), 
  file = fs::path(project_root, "all_transcripts.txt")
)




```

#Generating different transcripts for boys and girls.
```{r}

d_utterances_to_girls <- 
  d_utterances_arranged %>% 
  filter(target_child_sex == "female")

groups_girls <- 
  d_utterances_to_girls %>% 
  group_by(transcript_id) %>% 
  group_split

transcript_list_girls <- 
  groups_girls %>% 
  map(collapse_words)

write_file(
  transcript_list_girls %>% paste(collapse = "\n\n"),
  file = fs::path(project_root, "girl_transcripts.txt")
)

d_utterances_to_boys <- 
  d_utterances_arranged %>% 
  filter(target_child_sex == "male")

groups_boys <- 
  d_utterances_to_boys %>% 
  group_by(transcript_id) %>% 
  group_split

transcript_list_boys <- 
  groups_boys %>%
  map(collapse_words)

write_file(
  transcript_list_boys %>% paste(collapse = "\n\n"),
  file = fs::path(project_root, "boy_transcripts.txt")
)

```

```{r}

girl_words <- 
  c(
    "woman",
    "girl",
    "sister",
    "she",
    "her",
    "daughter"
  )

boy_words <- 
  c(
    "man",
    "boy",
    "brother",
    "he",
    "him",
    "son"
  )
  

```


```{r}

txt <- read_lines(fs::path(project_root, "all_transcripts.txt")) %>% tolower()

it <- itoken(txt, progressbar = FALSE)

vocab <- 
  text2vec::create_vocabulary(it) %>% 
  prune_vocabulary(term_count_min = 5)

vectorizer <- vocab_vectorizer(vocab)

childes_tcm <- create_tcm(it, vectorizer, skip_grams_window = 5)

glove <- GlobalVectors$new(rank = 300, x_max = 10)

word_vectors <- glove$fit_transform(childes_tcm, n_iter = 20, convergence_tol = 0.001)

word_vectors_context <- glove$components

full_vectors <- word_vectors + t(word_vectors_context)



```

```{r}
girl <- full_vectors["girl", , drop = F]

glove_girl_sims <- 
  text2vec::sim2(
    x = full_vectors, 
    y = girl, 
    method = "cosine", 
    norm = "l2"
  ) %>% 
  as_tibble(rownames = NA) %>% 
  rename(similarity_to_girl = girl) %>% 
  arrange(-similarity_to_girl) %>% 
  rownames_to_column("word")

boy <- full_vectors["boy", , drop = F]

glove_boy_sims <- 
  text2vec::sim2(
    x = full_vectors, 
    y = boy, 
    method = "cosine", 
    norm = "l2"
  ) %>% 
  as_tibble(rownames = NA) %>% 
  rename(similarity_to_boy = boy) %>% 
  arrange(-similarity_to_boy) %>% 
  rownames_to_column("word")




```

#Word2Vec

```{r}

#w2v <- word2vec(txt, type = "cbow", dim = 50, iter = 20)

w2v_tibble <- read_csv(fs::path(project_root, "full_w2v_300.csv"))

w2v <- 
  w2v_tibble %>% 
  as.matrix(rownames = "rowname")




w2v_girl_sims <- 
  w2v['girl',] %>% 
  word2vec_similarity(
    y = w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rename(similarity_to_girl = V1) %>% 
  arrange(-similarity_to_girl) %>% 
  rownames_to_column("word")


w2v_boy_sims <- 
  w2v['boy',] %>% 
  word2vec_similarity(
    y = w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rename(similarity_to_boy = V1) %>% 
  arrange(-similarity_to_boy) %>% 
  rownames_to_column("word")



```

## Boy and girl specific word2vecs
```{r}
#word2vec on speech to boys
boy_txt <- read_lines(fs::path(project_root, "boy_transcripts.txt")) %>% tolower()

boy_w2v <- word2vec(boy_txt, type = "cbow", iter = 20)

boy_w2v <- as.matrix(boy_w2v)

boy_w2v_tibble <- as_tibble(boy_w2v, rownames = NA)

#word2vec on speech to girls
girl_txt <- read_lines(fs::path(project_root, "girl_transcripts.txt")) %>% tolower()

girl_w2v <- word2vec(girl_txt, type = "cbow", iter = 20)

girl_w2v <- as.matrix(girl_w2v)

girl_w2v_tibble <- as_tibble(girl_w2v, rownames = NA)



```

```{r}
#get similarity to boy and girl clusters

#In speech to girls, what are the top similar words to the girl cluster?
girl_w2v_girl_set_sims <- 
  girl_w2v[girl_words,] %>% 
  word2vec_similarity(
    y = girl_w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_girls = avg)

#In speech to girls, what are the top similar words to the boy cluster?
girl_w2v_boy_set_sims <- 
  girl_w2v[boy_words,] %>% 
  word2vec_similarity(
    y = girl_w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_girls = avg)

#In speech to boys, what are the top similar words to the girl cluster?
boy_w2v_girl_set_sims <- 
  boy_w2v[girl_words,] %>% 
  word2vec_similarity(
    y = boy_w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_boys = avg)

#In speech to boys, what are the top similar words to the boy cluster?
boy_w2v_boy_set_sims <- 
  boy_w2v[boy_words,] %>% 
  word2vec_similarity(
    y = boy_w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_boys = avg)

#condensed version of similarity to girl words in girl-directed corpus
to_girl_girl_sims <- 
  girl_w2v_girl_set_sims %>% 
  select(word, to_girl_rank = rowid)

#condensed version of similarity to boy words in girl-directed corpus
to_girl_boy_sims <- 
  girl_w2v_boy_set_sims %>% 
  select(word, to_girl_rank = rowid)

#condensed version of similarity to girl words in boy-directed corpus
to_boy_girl_sims <- 
  boy_w2v_girl_set_sims %>% 
  select(word, to_boy_rank = rowid)

#condensed version of similarity to boy words in boy-directed corpus 
to_boy_boy_sims <- 
  boy_w2v_boy_set_sims %>% 
  select(word, to_boy_rank = rowid)

#frequency of words in girl-directed speech
girl_freqs <- tm::termFreq(girl_txt)

girl_freqs_tibble <- 
  as_tibble(girl_freqs, rownames = NA) %>% 
  rownames_to_column() %>% 
  arrange(-value)

difference_between_girl_sets <- 
  to_girl_girl_sims %>% 
  inner_join(to_boy_girl_sims, by = "word") %>% 
  mutate(diff = to_girl_rank - to_boy_rank) %>% 
  left_join(girl_freqs_tibble, by = c("word" = "rowname"))

girl_set_common_and_girly <- 
  difference_between_girl_sets %>% 
  arrange(to_girl_rank) %>% 
  mutate(abs_diff = abs(diff)) %>% 
  filter(to_girl_rank < 100) %>% 
  arrange(diff)

girl_set_common_and_girly %>% 
  filter(abs_diff < 1200) %>% 
  ggplot(aes(diff, value)) +
  geom_point() +
  coord_cartesian(xlim = c(-1250,100 ))




```



```{r}
full_similarities_glove <- 
  glove_boy_sims %>% 
  left_join(
    glove_girl_sims,
    by = "word"
  ) %>% 
  pivot_longer(
    starts_with("sim"),
    names_to = "gender",
    values_to = "sim_score_glove"
  )

full_similarities_w2v <- 
  w2v_boy_sims %>% 
  left_join(
    w2v_girl_sims,
    by = "word"
  ) %>% 
  pivot_longer(
    starts_with("sim"),
    names_to = "gender",
    values_to = "sim_score_w2v"
  )

full_sims_both_models <- 
  full_similarities_glove %>% 
  left_join(
    full_similarities_w2v,
    by = c("word", "gender")
  )

full_sims_both_models %>% 
  #filter(sim_score_glove < 0.5) %>% 
  mutate(gender = fct_recode(
    gender,
    `Similarity to 'boy'` = "similarity_to_boy",
    `Similarity to 'girl'` = "similarity_to_girl"
  )) %>% 
  ggplot(aes(
    x = sim_score_glove,
    y = sim_score_w2v
  )) +
  geom_hex() +
  facet_wrap(~gender) +
  scale_fill_viridis() +
  geom_smooth(method = "loess", color = "red") +
  labs(
    x = "Cosine distance (GloVe)",
    y = "Cosine distance (Word2Vec)",
    fill = "Number of words"
  ) +
  theme_minimal()
 
  
```




```{r}

glove_girl_set <- 
  full_vectors[rownames(full_vectors) %in% girl_words, ,drop = F]

glove_girl_set_sims <- 
  text2vec::sim2(
    x = full_vectors, 
    y = glove_girl_set, 
    method = "cosine", 
    norm = "l2"
  ) %>% 
  as_tibble(rownames = NA) %>%
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(daughter, woman, sister, girl, her, she))) %>% 
  arrange(-avg)

glove_boy_set <- 
  full_vectors[rownames(full_vectors) %in% boy_words, ,drop = F]

glove_boy_set_sims <- 
   text2vec::sim2(
    x = full_vectors, 
    y = glove_boy_set, 
    method = "cosine", 
    norm = "l2"
  ) %>% 
  as_tibble(rownames = NA) %>%
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(son, man, brother, boy, him, he))) %>% 
  arrange(-avg)


```


```{r}

w2v_girl_set_sims <- 
  w2v[girl_words,] %>% 
  word2vec_similarity(
    y = w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg)

w2v_boy_set_sims <- 
  w2v[boy_words,] %>% 
  word2vec_similarity(
    y = w2v,
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg)


```


```{r}
set_similarities_glove <- 
  glove_boy_set_sims %>% 
  select(word, avg_boy = avg) %>% 
  left_join(
    glove_girl_set_sims %>% select(word, avg_girl = avg),
    by = "word"
  ) %>% 
  pivot_longer(
    starts_with("avg"),
    names_to = "gender",
    values_to = "sim_score_glove"
  )

set_similarities_w2v <- 
  w2v_boy_set_sims %>% 
  select(word, avg_boy = avg) %>% 
  left_join(
    w2v_girl_set_sims %>% select(word, avg_girl = avg),
    by = "word"
  ) %>% 
  pivot_longer(
    starts_with("avg"),
    names_to = "gender",
    values_to = "sim_score_w2v"
  )

set_sims_both_models <- 
  set_similarities_glove %>% 
  left_join(
    set_similarities_w2v,
    by = c("word", "gender")
  )

set_sims_both_models %>% 
  #filter(sim_score_glove < 0.5) %>% 
  mutate(gender = fct_recode(
    gender,
    `Similarity to 'boy' words` = "avg_boy",
    `Similarity to 'girl' words` = "avg_girl"
  )) %>% 
  ggplot(aes(
    x = sim_score_glove,
    y = sim_score_w2v
  )) +
  geom_hex(bins = c(30, 60)) +
  facet_wrap(~gender) +
  scale_fill_viridis() +
  geom_smooth(method = "loess", color = "red") +
  labs(
    x = "Cosine distance (GloVe)",
    y = "Cosine distance (Word2Vec)",
    fill = "Number of words"
  ) +
  ggthemes::theme_few()
  
```

# Similarity to human judgements

```{r}

human_judgements <- 
  read_csv(
    file = fs::path(project_root, "human_ratings", "gender_ratings_mean.csv")
  )

differences_glove <- 
  set_similarities_glove %>% 
  pivot_wider(
    id_cols = word, 
    names_from = gender, 
    values_from = sim_score_glove
  ) %>% 
  mutate(difference_glove = avg_girl - avg_boy) %>% 
  select(word, difference_glove)

differences_w2v <- 
  set_similarities_w2v %>% 
  pivot_wider(
    id_cols = word, 
    names_from = gender, 
    values_from = sim_score_w2v
  ) %>% 
  mutate(difference_w2v = avg_girl - avg_boy) %>% 
  select(word, difference_w2v)

both_model_differences <- 
  differences_glove %>% 
  left_join(differences_w2v, by = "word")

human_rating_diffs <- 
  both_model_differences %>% 
  pivot_longer(
    cols = starts_with("difference"),
    names_to = "model"
  ) %>% 
  inner_join(
    human_judgements %>% select(word, mean),
    by = "word"
  )

human_rating_diffs %>% 
  mutate(model = fct_recode(
    model,
    `GloVe` = "difference_glove",
    `Word2Vec` = "difference_w2v"
  )) %>% 
  group_by(model) %>% 
  mutate(value = (value - mean(value, na.rm = TRUE))/sd(value, na.rm = TRUE)) %>% 
  ggplot(aes(mean, value)) +
  facet_wrap(~model) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm") +
  labs(
    x = "Human ratings (1 = most masculine, 5 = most feminine)",
    y = "Word embedding difference score (z-scored)\n(Higher = more girl-like)"
  ) +
  ggthemes::theme_few()
  
  

```


```{r}

#just looking at girl-directed speech, how do the embeddings correlate with human ratings
human_diffs_girl_directed_speech <- 
  girl_w2v_girl_set_sims %>% 
  select(word, sim_to_girl_words = to_girls) %>% 
  left_join(
    girl_w2v_boy_set_sims %>% select(word, sim_to_boy_words = to_girls),
    by = "word"
  ) %>% 
  mutate(diff = sim_to_girl_words - sim_to_boy_words) %>% 
  inner_join(
    human_judgements %>% select(word, rating = mean),
    by = "word"
  ) %>% 
  select(word, diff, rating) %>% 
  mutate(target = "girl-directed")

human_diffs_boy_directed_speech <- 
  boy_w2v_girl_set_sims %>% 
  select(word, sim_to_girl_words = to_boys) %>% 
  left_join(
    boy_w2v_boy_set_sims %>% select(word, sim_to_boy_words = to_boys),
    by = "word"
  ) %>% 
  mutate(diff = sim_to_girl_words - sim_to_boy_words) %>% 
  inner_join(
    human_judgements %>% select(word, rating = mean),
    by = "word"
  ) %>% 
  select(word, diff, rating) %>% 
  mutate(target = "boy-directed")

full_human_diffs <- 
  bind_rows(
    human_diffs_boy_directed_speech, 
    human_diffs_girl_directed_speech
  ) 

full_human_diffs %>% 
  ggplot(aes(rating, diff)) +
  facet_wrap(~target) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", color = "red") +
  viridis::scale_fill_viridis() +
  coord_cartesian(ylim = c(-.3, .3)) +
  labs(
    x = "Human ratings (1 = most masculine, 5 = most feminine)",
    y = "Word embedding difference score (z-scored)\n(Higher = more girl-like)"
  ) +
  ggthemes::theme_few()





```

#IAT stuff

```{r}


X <- c("woman", "girl", "sister", "she", "her", "daughter")

Y <- c("man", "boy", "brother", "he", "him", "son")

home <- c("family", "parent", "children", "home", "cousin", "wedding")

work <- c("job", "work", "money", "office", "business", "desk")

language <- c("book", "read", "write", "story", "letter", "spell")

math <- c("number", "count", "sort", "size", "shape", "different")

good <- c("good", "happy", "gift", "sunshine", "heaven")

bad <- c("bad", "awful", "sick", "trouble", "hurt")

  
calculate_weat <- function(mat, X, Y, A, B) {
  
  x_a <- vector("list")
  
  y_a <- vector("list")
  
  for (x in X) {
    this_x_diffs <- vector("list")
    for (a in A) {
      this_sim = word2vec_similarity(mat[x, ], mat[a, ], type = "cosine")
      this_x_diffs <- append(this_x_diffs, this_sim)
    }
    this_avg_sim <- mean(unlist(this_x_diffs))
    x_a <- append(x_a, this_avg_sim)
  }
  
  for (y in Y) {
    this_x_diffs <- vector("list")
    for (a in A) {
      this_sim = word2vec_similarity(mat[y, ], mat[a, ], type = "cosine")
      this_y_diffs <- append(this_x_diffs, this_sim)
    }
    this_avg_sim <- mean(unlist(this_y_diffs))
    y_a <- append(y_a, this_avg_sim)
  }
  
  numerator <- mean(unlist(x_a)) - mean(unlist(y_a))
  
  denom <- sd(unlist(c(x_a, y_a)))
  
  return(numerator/denom)
  
}

overall_home_work <- calculate_weat(w2v, X, Y, home, work)

to_girls_home_work <- calculate_weat(girl_w2v, X, Y, home, work)

to_boys_home_work <- calculate_weat(boy_w2v, X, Y, home, work)

overall_language_math <- calculate_weat(w2v, X, Y, language, math)

to_girls_language_math <- calculate_weat(girl_w2v, X, Y, language, math)

to_boys_language_math <- calculate_weat(boy_w2v, X, Y, language, math)

overall_good_bad <- calculate_weat(w2v, X, Y, good, bad)

to_girls_good_bad <- calculate_weat(girl_w2v, X, Y, good, bad)

to_boys_good_bad <- calculate_weat(boy_w2v, X, Y, good, bad)


```


```{r}

calculate_null <- function(mat, X, Y, A, B, n = 1000) {
  effects_vec <- vector("list")
  for (i in 1:n) {
    xy <- append(X, Y)
    shuffled_xy <- sample(xy)
    new_x <- shuffled_xy[1:6]
    new_y <- shuffled_xy[7:12]
    effects_vec <- append(effects_vec, calculate_weat(mat, new_x, new_y, A, B))
  }
  return(effects_vec %>% unlist)
}

overall_home_work_null <- calculate_null(w2v, X, Y, home, work)

to_girls_home_work_null <- calculate_null(girl_w2v, X, Y, home, work)

to_boys_home_work_null <- calculate_null(boy_w2v, X, Y, home, work)

overall_language_math_null <- calculate_null(w2v, X, Y, language, math)

to_girls_language_math_null <- calculate_null(girl_w2v, X, Y, language, math)

to_boys_language_math_null <- calculate_null(boy_w2v, X, Y, language, math)

overall_good_bad_null <- calculate_null(w2v, X, Y, good, bad)

to_girls_good_bad_null <- calculate_null(girl_w2v, X, Y, good, bad)

to_boys_good_bad_null <- calculate_null(boy_w2v, X, Y, good, bad)


```


```{r}

#Building a tibble for the plot.

weat_plot_tibble <- 
  tribble(
    ~stereotype, ~target, ~effect_size, ~sd,
    "home_work", "overall", overall_home_work, sd(overall_home_work_null),
    "home_work", "girls", to_girls_home_work, sd(to_girls_home_work_null),
    "home_work", "boys", to_boys_home_work, sd(to_boys_home_work_null),
    "good_bad", "overall", overall_good_bad, sd(overall_good_bad_null),
    "good_bad", "girls", to_girls_good_bad, sd(to_girls_good_bad_null),
    "good_bad", "boys", to_boys_good_bad, sd(to_boys_good_bad_null),
    "language_math", "overall", overall_language_math, sd(overall_language_math_null),
    "language_math", "girls", to_girls_language_math, sd(to_girls_language_math_null),
    "language_math", "boys", to_boys_language_math, sd(to_boys_language_math_null)
  ) %>% 
  mutate(
    errorbar_lower = effect_size - (1.96 * sd),
    errorbar_upper = effect_size + (1.96 * sd)
  )

weat_plot_tibble %>% 
  mutate(stereotype = fct_recode(
    stereotype,
    "Female-Good/\nMale-Bad" = "good_bad",
    "Female-Home/\nMale-Work" = "home_work",
    "Female-Language/\nMale-Math" = "language_math"
  )) %>% 
  ggplot(aes(x= stereotype, fill = target)) +
  geom_col(position = "dodge", aes(y = effect_size)) +
  geom_hline(aes(yintercept = 0), linetype = "dotted") +
  geom_errorbar(
    position = position_dodge(0.9),
    aes(ymin = errorbar_lower, ymax = errorbar_upper), 
    width = 0.3
  ) +
  scale_fill_viridis_d(option = "D") +
  ggthemes::theme_few() + 
  labs(y = "Implicit Bias effect size (Cohen's D)", fill = "Corpus") +
  theme(axis.title.x = element_blank())
```


```{r}

cdi_words <- 
  c("airplane", "bear", "boat", "car", "ball", "book", "meat", "duck", "game", "hat", "broom", "tray", "necklace", "comb", "towel", "show", "mop", "bed", "sock", "plate", "trash", "beach", "oven", "stair", "flag", "star", "swing", "school", "sky", "party", "friend", "mommy", "person", "carry", "chase", "finish", "fit", "hug", "listen", "like", "pretend", "rip", "shake", "taste", "think", "wish")

cds_cdi_to_feminine <- 
  w2v[girl_words,] %>% 
  word2vec_similarity(
    y = w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_girls = avg) %>% 
  select(word, to_girls)

cds_cdi_to_masculine <- 
  w2v[boy_words,] %>% 
  word2vec_similarity(
    y = w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_boys = avg) %>% 
  select(word, to_boys)

gds_cdi_to_feminine <- 
  girl_w2v[girl_words,] %>% 
  word2vec_similarity(
    y = girl_w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_girls = avg) %>% 
  select(word, to_girls) 

gds_cdi_to_masculine <- 
  girl_w2v[boy_words,] %>% 
  word2vec_similarity(
    y = girl_w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_boys = avg) %>% 
  select(word, to_boys)

bds_cdi_to_feminine <- 
  boy_w2v[girl_words,] %>% 
  word2vec_similarity(
    y = boy_w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(woman, girl, sister, she, her, daughter))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_girls = avg) %>% 
  select(word, to_girls)

bds_cdi_to_masculine <- 
  boy_w2v[boy_words,] %>% 
  word2vec_similarity(
    y = boy_w2v[cdi_words,],
    type = "cosine"
  ) %>% 
  t() %>% 
  as_tibble(rownames = NA) %>% 
  rownames_to_column("word") %>% 
  rowwise() %>% 
  mutate(avg = mean(c(man, boy, brother, he, him, son))) %>% 
  arrange(-avg) %>% 
  rowid_to_column() %>% 
  rename(to_boys = avg) %>% 
  select(word, to_boys)

cds_diff <- 
  cds_cdi_to_feminine %>% 
  left_join(cds_cdi_to_masculine, by = "word") %>% 
  mutate(diff = to_girls - to_boys, dataset = "Overall") %>% 
  arrange(-diff)

gds_diff <- 
  gds_cdi_to_feminine %>% 
  left_join(gds_cdi_to_masculine, by = "word") %>% 
  mutate(diff = to_girls - to_boys, dataset = "Girl-directed speech") %>% 
  arrange(-diff)

bds_diff <- 
  bds_cdi_to_feminine %>% 
  left_join(gds_cdi_to_masculine, by = "word") %>% 
  mutate(diff = to_girls - to_boys, dataset = "Boy-directed speech") %>% 
  arrange(-diff)

all_diff <- 
  bind_rows(cds_diff, gds_diff, bds_diff) %>% 
  pivot_longer(cols = starts_with("to"), names_to = "anchors", values_to = "cosine_sim_to_anchors")

all_diff$word <- fct_reorder(all_diff$word, all_diff$diff)

all_diff %>% 
  mutate(
    word = fct_reorder(word, diff),
    dataset = fct_relevel(dataset, "Overall")
  ) %>% 
  ggplot(aes(diff, fct_inorder(word))) +
  facet_wrap(~dataset) +
  geom_point() + 
  theme_minimal() +
  labs(
    x = "(Mean cosine distance from 'girl' anchors) - (Mean cosine distance from 'boy' anchors)"
  ) +
  theme(axis.title.y = element_blank())



  


```


